# Generated by Django 3.2.8 on 2021-10-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
